server:
  port: 18080
  shutdown: graceful

jwt:
  secret: "your-256-bit-secret-key-should-be-long-enough"
  expiration: 86400000 # 1? (???)

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true