server:
  port: 18080
  shutdown: graceful

jwt:
  secret: "your-256-bit-secret-key-should-be-long-enough"
  access-expiration: 900000    # Access Token 만료 (15분)
  refresh-expiration: 1209600000 # Refresh Token 만료 (14일)

openai:
  api:
    key: "{$api-key}"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true